# Generated by Django 2.1.3 on 2018-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='BookForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
